global:
  checkNewVersion: false
  sendAnonymousUsage: false

entryPoints:
  web:
    address: :80
    forwardedHeaders:
      trustedIPs:
        - 127.0.0.1/32

providers:
  file:
    directory: /etc/traefik/dynamic
    watch: true

api:
  dashboard: false

ping: {}

metrics:
  prometheus:
    addEntryPointsLabels: true
    addRoutersLabels: true
    addServicesLabels: true

accessLog:
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: drop
      names:
        User-Agent: keep
        X-Correlation-Id: keep

log:
  format: json
  level: INFO
